### ISSUE TITLE
Update ReadMe to adding new password setting command

### ISSUE THREAD

**Issue by dperryazauditor** [azauditor/LinuxAudit#1]
Update to Password Settings section of ReadMe to:

## Password Settings

These 2 commands will show all accounts and the password settings that are being applied to them. Run both as each outputs different components of the password settings.

Minimum and maximum password age:
``` Bash
sudo passwd --status --all > PasswordSetting.txt
```
Password length and complexity:
``` Bash
sudo /etc/security/pwquality.conf > Pwquality.txt
```

**Alternative Commands:**
Run if the above command for minimum and maximum password age does not work.

``` Bash
sudo passwd -S -a > PasswordSetting.txt
```

If you are running **Oracle Enterprise Linux Server** use the following command. **Note**: You **MUST** run this command as root otherwise it will fail.

``` Bash
for u in `cat /etc/passwd | cut -d: -f1 | sort`; do passwd -S $u >> PasswordSetting.txt; done
```

If you are running **UNIX** use the following command. **Note**: You **MUST** run this command in the /etc/ folder otherwise it will fail.

``` Bash
passwd -s -a > PasswordSetting.txt
```

**Comment by AZphanus** [comment]
Updated Password section
